# Description: Template configuration file for training process with explanations for each field.
# Make sure to adapt based on your dataset and requirements as well as computational resources.

# Required fields (no default values):
model_name: model_name_here # Name of the model. Used for saving outputs. (required)
output_path: path/to/output # Path to save outputs (required)
datasets: # List of datasets to be used for training
  - name: DataSet-1      # Name of the dataset (required)
    path: path/to/dataset-1 # Path to the dataset (required)
    transforms: # List of ordered transformations to be applied to the dataset, choose order and type based on your dataset and model
      # Rotate using torchvision.transforms.functional.rotate
      - rotate: {degrees: -90}
            # degrees (float or int) – Angle to rotate the image, in degrees. NOTE: Positive values mean counter-clockwise rotation.
      
      # Resize
      # - Note: Resize should be used with caution, as it may distort the image aspect ratio.
      - resize : {height: 96, width: 96}
            # height (int) – Desired height of the output image.
            # width (int) – Desired width of the output image.

      # Crop using torchvision.transforms.functional.crop
      - crop : {top : 0, left: 0, height: 96, width: 96}
            # top (int) – Vertical component of the top left corner of the crop box.
            # left (int) – Horizontal component of the top left corner of the crop box.
            # height (int) – Height of the crop box.
            # width (int) – Width of the crop box.

      # Bottom center crop using PIL.crop
      - CenterCrop: {side: "bottom", height: 96, width: 96} # Crop the bottom center 96x96 region
            # height (int) – Height of the crop box.
            # width (int) – Width of the crop box.
      
      - save_img : {n: 50, save_dir: "data/transforms_debug/dataset"} # Save every nth image to the specified directory for debugging
      # ToTensor using torchvision.transforms.ToTensor
      # Converts a PIL Image or numpy.ndarray (H x W x C) in the range [0, 255] to a torch.FloatTensor of shape (C x H x W) in the range [0.0, 1.0]
      - ToTensor 

      # Normalization using torchvision.transforms.Normalize
      - normalize: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
            # mean (sequence) – Sequence of means for each channel.
            # std (sequence) – Sequence of standard deviations for each channel.

  - name: DataSet-1      # Name of the dataset
    path: path/to/dataset-1 # Path to the dataset
    transforms: # Again list of ordered transformations to be applied to the dataset, choose based on your dataset and model
      - rotate: {degrees: +90}
      # ... (other transforms as needed)


# Non-required fields (default values available):
batch_size: 32 # Batch size for training (default: 32)
patience: 5 # Patience for early stopping, to disable set to 0 (default: 5)
model_type: squeezenet # Type of the model. Choose from enum: ["shufflenet", "mobilenet", "efficientnet", "efficientnet_b0", "densenet", "squeezenet", "mnasnet"] (default: squeezenet)
num_workers: 4 # Number of workers for data loading (default: 4)

# Transfer Learning configuration
transfer_learning_epochs: 10  # Epochs for transfer learning phase (default: 10)
transfer_learning_rate: 0.001  # Learning rate for transfer learning (default: 0.001)
transfer_weight_decay: 0.0001  # Weight decay for transfer learning (default: 0.0001)

# Fine-tuning configuration
fine_tune: True # Whether to perform fine-tuning after transfer learning (default: False)
fine_tune_epochs: 10 # Epochs for fine-tuning phase (default: 10)
fine_tuning_learning_rate: 0.0001 # Learning rate for fine-tuning (default: 0.0001)
fine_tuning_weight_decay: 0.0001 # Weight decay for fine-tuning (default: 0.0001)
num_unfreezed_feature_layers: 2  # Number of last feature layers to unfreeze during fine-tuning (default: 2)

# Additional parameters
requires_grad: False # Whether to require gradients for the model parameters (make them trainable) (default: False)
check_corrupted_images: True # Whether to check for corrupted images in the dataset (default: False)
pin_memory - True # Whether to pin memory during data loading (default: True)
profile - False  # Whether to profile the training process (causing training to be interrupted after few steps) (default: False) | FOR DEBUGGING ONLY
